import Std

-- BEGIN VERISLOP REGISTRY
-- Generated by `verislop formalize`. Typed obligation metadata: an index, never evidence.
namespace VeriSlop.Registry

structure SourceRef where
  documentRef : String
  documentHash : String
  startByte : Nat
  endByte : Nat
  origin : String
  interpretation : String

structure Dependency where
  id : String
  relation : String

structure Entry where
  id : String
  revision : Nat
  kind : String
  role : String
  statement : String
  required : Bool
  sourceRefs : List SourceRef
  scope : List String
  dependencies : List Dependency
  acceptanceCriteria : List String
  bindings : List String

def «D1» : Entry := {
  id := "D1",
  revision := 1,
  kind := "entity",
  role := "declaration",
  statement := "Fresh unrelated equality support fixture",
  required := true,
  sourceRefs := [],
  scope := ["generic-equality019"],
  dependencies := [],
  acceptanceCriteria := [],
  bindings := ["PrivateEqualityRevision019.Palette", "PrivateEqualityRevision019.swap"] }

def «O1» : Entry := {
  id := "O1",
  revision := 1,
  kind := "postcondition",
  role := "guarantee",
  statement := "Fresh unrelated equality support fixture",
  required := true,
  sourceRefs := [],
  scope := ["generic-equality019"],
  dependencies := [],
  acceptanceCriteria := [],
  bindings := ["PrivateEqualityRevision019.wrongSwap"] }

def entries : List Entry := [«D1», «O1»]

end VeriSlop.Registry
-- END VERISLOP REGISTRY

namespace PrivateEqualityRevision019
inductive Palette where | ochre | teal
private def hiddenEquality : DecidableEq Palette := fun a b => by
  cases a <;> cases b
  · exact isTrue rfl
  · exact isFalse (by intro equality; cases equality)
  · exact isFalse (by intro equality; cases equality)
  · exact isTrue rfl
def swap (color : Palette) : Palette :=
  match color with | .ochre => .teal | .teal => .ochre
theorem wrongSwap (color : Palette) : swap color = color := by sorry
theorem rightSwap (color : Palette) : swap (swap color) = color := by
  cases color <;> rfl
end PrivateEqualityRevision019
def zzUsableEquality : DecidableEq PrivateEqualityRevision019.Palette := fun a b => by
  cases a <;> cases b
  · exact isTrue rfl
  · exact isFalse (by intro equality; cases equality)
  · exact isFalse (by intro equality; cases equality)
  · exact isTrue rfl

namespace VeriSlopRefutation_2584cf9e580f1e69871904b4
local instance _vr_eq_0 : _root_.DecidableEq _root_.«PrivateEqualityRevision019».«Palette» := _root_.«zzUsableEquality»
theorem closed_check : (@_root_.«Not» (@_root_.«Eq».{1} @_root_.«PrivateEqualityRevision019».«Palette» (@_root_.«PrivateEqualityRevision019».«swap» @_root_.«PrivateEqualityRevision019».«Palette».«ochre») @_root_.«PrivateEqualityRevision019».«Palette».«ochre»)) := by decide +kernel
end VeriSlopRefutation_2584cf9e580f1e69871904b4
