"""Write-once source-only generic mock checks; no live models/VIEW/Lean/tasks."""
import ast
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path
import subprocess
import sys
import time

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[1]


def identity(path):
    raw = path.read_bytes()
    return {"sha256": "sha256:" + hashlib.sha256(raw).hexdigest(), "bytes": len(raw)}


def json_file(path, value):
    with path.open("x", encoding="utf-8") as stream:
        json.dump(value, stream, sort_keys=True, indent=2, allow_nan=False)
        stream.write("\n")


def main():
    output = HERE / "source-checks"
    if output.exists() or (HERE / "SEAL.sha256").exists():
        raise ValueError("SOURCE_CHECKS_OR_SEALED_CANDIDATE_ALREADY_EXIST")
    # Exclude only this package's generated bytecode, never repository inputs.
    sources = {path.relative_to(ROOT).as_posix(): identity(path)
               for path in HERE.rglob("*") if path.is_file() and "__pycache__" not in path.parts}
    baseline = ROOT / "synthetic_dataset/tools/bootstrap_tier2_carrier_view.py"
    baseline_identity = identity(baseline)
    assert baseline_identity["sha256"] == "sha256:9930beff878848b05c8d69245fff12c1388f14254b6630504b36748c4c294366"
    test_ids = []
    for filename in ("test_checkpoint_candidate.py", "test_collector_candidate.py"):
        tree = ast.parse((HERE / filename).read_text())
        for node in tree.body:
            if isinstance(node, ast.ClassDef):
                test_ids += [filename[:-3] + "." + node.name + "." + child.name for child in node.body
                             if isinstance(child, ast.FunctionDef) and child.name.startswith("test_")]
    test_ids.sort()
    assert len(test_ids) == 21
    argv = [sys.executable, "-B", "-m", "unittest", "discover", "-s", str(HERE), "-p", "test_*.py", "-v"]
    environment = os.environ.copy()
    environment["PYTHONDONTWRITEBYTECODE"] = "1"
    environment["PYTHONPATH"] = str(ROOT)
    output.mkdir()
    registration = {"format": "verislop.candidate003-source-check-registration/1", "status": "REGISTERED_NOT_EXECUTED",
                    "argv": argv, "cwd": str(ROOT), "timeout_seconds": None, "test_ids": test_ids,
                    "source_files": sources, "production_baseline": baseline_identity,
                    "actual_model_calls": 0, "actual_carrier_view_calls": 0, "actual_Lean_calls": 0,
                    "data": "Finite unrelated synthetic source/mock cases only, including exact Unicode SHA stdlib crosschecks.",
                    "authority": "Source prerequisite only; no runtime qualification/task TESTED/lifecycle/semantic-consumption authority."}
    json_file(output / "registration-before-execution.json", registration)
    started = datetime.now(timezone.utc).isoformat()
    clock_start = time.monotonic()
    with (output / "stdout.log").open("xb") as stdout, (output / "stderr.log").open("xb") as stderr:
        child = subprocess.Popen(argv, cwd=str(ROOT), env=environment, stdout=stdout, stderr=stderr)
        pid = child.pid
        returncode = child.wait()
    ended = datetime.now(timezone.utc).isoformat()
    wall = time.monotonic() - clock_start
    same_sources = all(identity(ROOT / name) == value for name, value in sources.items())
    same_baseline = identity(baseline) == baseline_identity
    receipt = {"format": "verislop.candidate003-actual-source-check-process/1", "argv": argv, "cwd": str(ROOT), "pid": pid,
               "started_at": started, "ended_at": ended, "wall_seconds": wall, "timeout_seconds": None,
               "exit_code": returncode, "source_guard_unchanged": same_sources, "production_guard_unchanged": same_baseline,
               "environment": {name: environment[name] for name in ("PYTHONDONTWRITEBYTECODE", "PYTHONPATH")},
               "stdout": identity(output / "stdout.log"), "stderr": identity(output / "stderr.log"),
               "actual_model_calls": 0, "actual_carrier_view_calls": 0, "actual_Lean_calls": 0,
               "scope": "Generic source/mock development checks only, not a qualification run or author result."}
    json_file(output / "actual-process-receipt.json", receipt)
    status = "SOURCE_ONLY_CHECKS_PASSED_RUNTIME_UNQUALIFIED" if returncode == 0 and same_sources and same_baseline else "SOURCE_ONLY_CHECKS_FAILED"
    summary = {"format": "verislop.candidate003-source-check-summary/1", "status": status, "test_count": len(test_ids),
               "test_ids": test_ids, "process_receipt": str((output / "actual-process-receipt.json").relative_to(ROOT)),
               "production_installed": False, "runtime_qualified": False, "semantic_acceptance_authority": False,
               "task_TESTED_authority": False, "view_full_inspection_or_consumption_attested": False}
    json_file(output / "summary.json", summary)
    print(json.dumps({"status": status, "exit_code": returncode, "source_guard_unchanged": same_sources,
                      "production_guard_unchanged": same_baseline, "test_count": len(test_ids), "pid": pid}, sort_keys=True))
    return 0 if status == "SOURCE_ONLY_CHECKS_PASSED_RUNTIME_UNQUALIFIED" else 1


if __name__ == "__main__":
    raise SystemExit(main())
