import Std
namespace VeriSlopAST
structure «Input» where
  «values» : (_root_.List _root_.Int)
  «minimum» : _root_.Int
  «factor» : _root_.Int
  «prefix» : _root_.String
structure «Output» where
  «values» : (_root_.List _root_.Int)
  «total» : _root_.Int
  «count» : _root_.Int
  «label» : _root_.String
def «solve» («_v0» : _root_.VeriSlopAST.«Input») : _root_.VeriSlopAST.«Output» := (_root_.VeriSlopAST.«Output».«mk» (@_root_.List.map _root_.Int _root_.Int (fun («_v1» : _root_.Int) => (_root_.Int.mul «_v1» (_root_.VeriSlopAST.«Input».«factor» «_v0»))) (@_root_.List.filter _root_.Int (fun («_v1» : _root_.Int) => (_root_.Decidable.decide ((_root_.VeriSlopAST.«Input».«minimum» «_v0») ≤ «_v1»))) (_root_.VeriSlopAST.«Input».«values» «_v0»))) (@_root_.List.foldl _root_.Int _root_.Int (fun («_v1» : _root_.Int) («_v2» : _root_.Int) => (_root_.Int.add «_v1» «_v2»)) (_root_.Int.ofNat 0) (@_root_.List.map _root_.Int _root_.Int (fun («_v1» : _root_.Int) => (_root_.Int.mul «_v1» (_root_.VeriSlopAST.«Input».«factor» «_v0»))) (@_root_.List.filter _root_.Int (fun («_v1» : _root_.Int) => (_root_.Decidable.decide ((_root_.VeriSlopAST.«Input».«minimum» «_v0») ≤ «_v1»))) (_root_.VeriSlopAST.«Input».«values» «_v0»)))) (_root_.Int.ofNat (@_root_.List.length _root_.Int (@_root_.List.map _root_.Int _root_.Int (fun («_v1» : _root_.Int) => (_root_.Int.mul «_v1» (_root_.VeriSlopAST.«Input».«factor» «_v0»))) (@_root_.List.filter _root_.Int (fun («_v1» : _root_.Int) => (_root_.Decidable.decide ((_root_.VeriSlopAST.«Input».«minimum» «_v0») ≤ «_v1»))) (_root_.VeriSlopAST.«Input».«values» «_v0»))))) (_root_.String.append (_root_.VeriSlopAST.«Input».«prefix» «_v0») "\"\\\x00\x08\x0cé🙂"))
theorem «_vs_body_solve» : (∀ («_v0» : _root_.VeriSlopAST.«Input»), ((_root_.VeriSlopAST.«solve» «_v0») = (_root_.VeriSlopAST.«Output».«mk» (@_root_.List.map _root_.Int _root_.Int (fun («_v1» : _root_.Int) => (_root_.Int.mul «_v1» (_root_.VeriSlopAST.«Input».«factor» «_v0»))) (@_root_.List.filter _root_.Int (fun («_v1» : _root_.Int) => (_root_.Decidable.decide ((_root_.VeriSlopAST.«Input».«minimum» «_v0») ≤ «_v1»))) (_root_.VeriSlopAST.«Input».«values» «_v0»))) (@_root_.List.foldl _root_.Int _root_.Int (fun («_v1» : _root_.Int) («_v2» : _root_.Int) => (_root_.Int.add «_v1» «_v2»)) (_root_.Int.ofNat 0) (@_root_.List.map _root_.Int _root_.Int (fun («_v1» : _root_.Int) => (_root_.Int.mul «_v1» (_root_.VeriSlopAST.«Input».«factor» «_v0»))) (@_root_.List.filter _root_.Int (fun («_v1» : _root_.Int) => (_root_.Decidable.decide ((_root_.VeriSlopAST.«Input».«minimum» «_v0») ≤ «_v1»))) (_root_.VeriSlopAST.«Input».«values» «_v0»)))) (_root_.Int.ofNat (@_root_.List.length _root_.Int (@_root_.List.map _root_.Int _root_.Int (fun («_v1» : _root_.Int) => (_root_.Int.mul «_v1» (_root_.VeriSlopAST.«Input».«factor» «_v0»))) (@_root_.List.filter _root_.Int (fun («_v1» : _root_.Int) => (_root_.Decidable.decide ((_root_.VeriSlopAST.«Input».«minimum» «_v0») ≤ «_v1»))) (_root_.VeriSlopAST.«Input».«values» «_v0»))))) (_root_.String.append (_root_.VeriSlopAST.«Input».«prefix» «_v0») "\"\\\x00\x08\x0cé🙂")))) := by intros; rfl
@[reducible] def «valid» («_v0» : _root_.VeriSlopAST.«Input») : Prop := ((_root_.VeriSlopAST.«Input».«minimum» «_v0») ≤ (_root_.Int.ofNat 0))
theorem «_vs_predicate_valid» («_v0» : _root_.VeriSlopAST.«Input») : ((_root_.VeriSlopAST.«valid» «_v0») ↔ ((_root_.VeriSlopAST.«Input».«minimum» «_v0») ≤ (_root_.Int.ofNat 0))) := by rfl
theorem «nonvacuity» : (∃ («_v0» : _root_.VeriSlopAST.«Input»), (_root_.VeriSlopAST.«valid» «_v0»)) := by sorry
theorem «observable» : (∀ («_v0» : _root_.VeriSlopAST.«Input»), ((_root_.VeriSlopAST.«valid» «_v0») → ((_root_.VeriSlopAST.«solve» «_v0») = (_root_.VeriSlopAST.«Output».«mk» (@_root_.List.map _root_.Int _root_.Int (fun («_v1» : _root_.Int) => (_root_.Int.mul «_v1» (_root_.VeriSlopAST.«Input».«factor» «_v0»))) (@_root_.List.filter _root_.Int (fun («_v1» : _root_.Int) => (_root_.Decidable.decide ((_root_.VeriSlopAST.«Input».«minimum» «_v0») ≤ «_v1»))) (_root_.VeriSlopAST.«Input».«values» «_v0»))) (@_root_.List.foldl _root_.Int _root_.Int (fun («_v1» : _root_.Int) («_v2» : _root_.Int) => (_root_.Int.add «_v1» «_v2»)) (_root_.Int.ofNat 0) (@_root_.List.map _root_.Int _root_.Int (fun («_v1» : _root_.Int) => (_root_.Int.mul «_v1» (_root_.VeriSlopAST.«Input».«factor» «_v0»))) (@_root_.List.filter _root_.Int (fun («_v1» : _root_.Int) => (_root_.Decidable.decide ((_root_.VeriSlopAST.«Input».«minimum» «_v0») ≤ «_v1»))) (_root_.VeriSlopAST.«Input».«values» «_v0»)))) (_root_.Int.ofNat (@_root_.List.length _root_.Int (@_root_.List.map _root_.Int _root_.Int (fun («_v1» : _root_.Int) => (_root_.Int.mul «_v1» (_root_.VeriSlopAST.«Input».«factor» «_v0»))) (@_root_.List.filter _root_.Int (fun («_v1» : _root_.Int) => (_root_.Decidable.decide ((_root_.VeriSlopAST.«Input».«minimum» «_v0») ≤ «_v1»))) (_root_.VeriSlopAST.«Input».«values» «_v0»))))) (_root_.String.append (_root_.VeriSlopAST.«Input».«prefix» «_v0») "\"\\\x00\x08\x0cé🙂"))))) := by sorry
end VeriSlopAST
