import Std

-- BEGIN VERISLOP REGISTRY
-- Generated by `verislop formalize`. Typed obligation metadata: an index, never evidence.
namespace VeriSlop.Registry

structure SourceRef where
  documentRef : String
  documentHash : String
  startByte : Nat
  endByte : Nat
  origin : String
  interpretation : String

structure Dependency where
  id : String
  relation : String

structure Entry where
  id : String
  revision : Nat
  kind : String
  role : String
  statement : String
  required : Bool
  sourceRefs : List SourceRef
  scope : List String
  dependencies : List Dependency
  acceptanceCriteria : List String
  bindings : List String

def «D1» : Entry := {
  id := "D1",
  revision := 1,
  kind := "entity",
  role := "declaration",
  statement := "Fresh unrelated equality support fixture",
  required := true,
  sourceRefs := [],
  scope := ["generic-equality019"],
  dependencies := [],
  acceptanceCriteria := [],
  bindings := ["RefutationEquality019.Token", "RefutationEquality019.ZLeaf", "RefutationEquality019.AParcel", "RefutationEquality019.swap", "RefutationEquality019.carry"] }

def «O1» : Entry := {
  id := "O1",
  revision := 1,
  kind := "postcondition",
  role := "guarantee",
  statement := "Fresh unrelated equality support fixture",
  required := true,
  sourceRefs := [],
  scope := ["generic-equality019"],
  dependencies := [],
  acceptanceCriteria := [],
  bindings := ["RefutationEquality019.wrongToken"] }

def entries : List Entry := [«D1», «O1»]

end VeriSlop.Registry
-- END VERISLOP REGISTRY

-- Fixture prerequisite: pinned Std does not provide Except DecidableEq.
deriving instance DecidableEq for Except
namespace RefutationEquality019
inductive Token where | amber | violet
  deriving DecidableEq
structure ZLeaf where
  token : Token
  amount : Nat
  deriving DecidableEq
structure AParcel where
  leaf : ZLeaf
  spare : Option Token
  history : List ZLeaf
  outcome : Except Token ZLeaf
  deriving DecidableEq
def swap (t : Token) : Token :=
  match t with | .amber => .violet | .violet => .amber
def carry (p : AParcel) : AParcel :=
  { p with leaf := { p.leaf with token := swap p.leaf.token } }
theorem wrongToken (t : Token) : swap t = t := by sorry
theorem rightToken (t : Token) : swap (swap t) = t := by cases t <;> rfl
theorem wrongParcel (p : AParcel) : carry p = p := by sorry
theorem rightParcel (p : AParcel) : carry (carry p) = p := by
  cases p with
  | mk leaf spare history outcome =>
    cases leaf with
    | mk token amount => cases token <;> rfl
end RefutationEquality019

namespace VeriSlopRefutation_e0ed87a86cc2df3ae6d37950
local instance _vr_eq_0 : _root_.DecidableEq _root_.«RefutationEquality019».«Token» := _root_.«RefutationEquality019».«instDecidableEqToken»
local instance _vr_eq_1 : _root_.DecidableEq _root_.«RefutationEquality019».«ZLeaf» := _root_.«RefutationEquality019».«instDecidableEqZLeaf»
local instance _vr_eq_2 : _root_.DecidableEq _root_.«RefutationEquality019».«AParcel» := _root_.«RefutationEquality019».«instDecidableEqAParcel»
theorem closed_check : (@_root_.«Not» (@_root_.«Eq».{1} @_root_.«RefutationEquality019».«Token» (@_root_.«RefutationEquality019».«swap» @_root_.«RefutationEquality019».«Token».«amber») @_root_.«RefutationEquality019».«Token».«amber»)) := by decide +kernel
end VeriSlopRefutation_e0ed87a86cc2df3ae6d37950
