
const assert = require('assert');
const input = JSON.parse(require('fs').readFileSync(0,'utf8'));
const ref={path:'/synthetic/reviewer-own.json',sha256:'sha256:'+'a'.repeat(64),request_sha256:'sha256:'+'b'.repeat(64)};
const fields={'/system':'é😀e\u0301\n','/user':'用户𝄞\\"'};
const inv={operation:'inventory',output_cap_bytes:8192,metadata_reserve_bytes:2048};
const view=(selector,start=0,cap=8192)=>({operation:'field',selector,start_char:start,output_cap_bytes:cap,metadata_reserve_bytes:2048});
function doc(v,end){
 const base={format:'verislop.exact-carrier-view/0.1',status:'ok',carrier_path:ref.path,carrier_raw_bytes:12345,carrier_sha256:ref.sha256,request_sha256:ref.request_sha256,request_id:'independent-generic',char_unit:'decoded_unicode_code_points',byte_unit:'decoded_field_utf8',output_cap_bytes:v.output_cap_bytes,metadata_reserve_bytes:v.metadata_reserve_bytes,operation:v.operation};
 if(v.operation==='inventory')return {...base,navigation:'complete_linear_fields_only',fields:['/system','/user'].map(selector=>({selector,field_chars:Array.from(fields[selector]).length,field_utf8_bytes:checkpointText(fields[selector]).bytes,start_char:0,end_char:Array.from(fields[selector]).length}))};
 const full=Array.from(fields[v.selector]);end=end===undefined?full.length:end;const content=full.slice(v.start_char,end).join('');
 return {...base,selector:v.selector,field_chars:full.length,field_utf8_bytes:checkpointText(full.join('')).bytes,start_char:v.start_char,end_char:end,start_utf8_byte:checkpointText(full.slice(0,v.start_char).join('')).bytes,end_utf8_byte:checkpointText(full.slice(0,end).join('')).bytes,content_chars:end-v.start_char,content_utf8_bytes:checkpointText(content).bytes,content,next_char:end,field_eof:end===full.length};
}
const pending=(v,end,chunk='owned-chunk')=>({reference:ref,view:v,result:{chunk_id:chunk,exit_code:0,original_token_count:100,wall_time_seconds:0.001,output:checkpointWire(doc(v,end))+'\n'}});
const ack=(chunk='owned-chunk')=>({chunk_id:chunk,outer_output_intact:true});
const copy=x=>JSON.parse(JSON.stringify(x));
const results=[];const check=(name,fn)=>{fn();results.push({id:name,status:'PASS'});};
let state=checkpointConfirm(undefined,pending(inv),ack(),ref);
const rejects=(name,mutate,error)=>check(name,()=>{const before=checkpointWire(state);const p=copy(pending(view('/system')));mutate(p);assert.throws(()=>checkpointConfirm(state,p,ack(),ref),new RegExp(error));assert.strictEqual(checkpointWire(state),before);});
rejects('status_bool',p=>p.result.exit_code=false,'ACTUAL_RESULT_NOT_COMPLETE');
rejects('status_nonzero',p=>p.result.exit_code=1,'ACTUAL_RESULT_NOT_COMPLETE');
rejects('status_missing',p=>delete p.result.exit_code,'ACTUAL_RESULT_NOT_COMPLETE');
rejects('running_session',p=>p.result.session_id=42,'ACTUAL_RESULT_NOT_COMPLETE');
rejects('chunk_mismatch',p=>p.result.chunk_id='other','ACTUAL_RESULT_NOT_COMPLETE');
rejects('nested_token_overflow',p=>p.result.original_token_count=16385,'NESTED_OUTPUT_TRUNCATION');
rejects('malformed_output',p=>p.result.output=p.result.output.slice(0,-9),'MALFORMED_OR_TRUNCATED');
rejects('duplicate_key_output',p=>p.result.output=p.result.output.slice(0,-2)+',"status":"ok"}\n','NONCANONICAL_OR_DUPLICATE');
rejects('wrong_raw_sha',p=>{const d=JSON.parse(p.result.output);d.carrier_sha256='sha256:'+'c'.repeat(64);p.result.output=checkpointWire(d)+'\n';},'ACTUAL_VIEW_IDENTITY');
rejects('wrong_request_sha',p=>{const d=JSON.parse(p.result.output);d.request_sha256='sha256:'+'c'.repeat(64);p.result.output=checkpointWire(d)+'\n';},'ACTUAL_VIEW_IDENTITY');
rejects('wrong_reference',p=>p.reference.path='/other.json','UNMATCHED_OWN_PENDING');
rejects('extra_view_key',p=>p.view.extra=true,'INVALID_CLOSED_OWN_VIEW');
rejects('extra_document_key',p=>{const d=JSON.parse(p.result.output);d.extra=true;p.result.output=checkpointWire(d)+'\n';},'INVALID_ACTUAL_VIEW_FIELDS');
rejects('boolean_cursor',p=>{const d=JSON.parse(p.result.output);d.end_char=true;p.result.output=checkpointWire(d)+'\n';},'INVALID_ACTUAL_CURSOR');
rejects('wrong_byte_total',p=>{const d=JSON.parse(p.result.output);d.content_utf8_bytes++;p.result.output=checkpointWire(d)+'\n';},'ACTUAL_CURSOR_LENGTH');
rejects('wrong_eof',p=>{const d=JSON.parse(p.result.output);d.field_eof=false;p.result.output=checkpointWire(d)+'\n';},'ACTUAL_CURSOR_LENGTH');
check('false_outer_ack_no_mutation',()=>{const before=checkpointWire(state);assert.throws(()=>checkpointConfirm(state,pending(view('/system')),{chunk_id:'owned-chunk',outer_output_intact:false},ref),/OUTER_OUTPUT_NOT_CONFIRMED/);assert.strictEqual(checkpointWire(state),before);});
check('system_before_user',()=>assert.throws(()=>checkpointConfirm(state,pending(view('/user')),ack(),ref),/SYSTEM_EOF_REQUIRED/));
check('gap_no_mutation',()=>assert.throws(()=>checkpointConfirm(state,pending(view('/system',1)),ack(),ref),/OWN_CURSOR_GAP/));
state=checkpointConfirm(state,pending(view('/system'),2),ack(),ref);
check('partial_unicode_exact',()=>{assert.strictEqual(state.fields['/system'].content,'é😀');assert.strictEqual(state.fields['/system'].next_char,2);assert.strictEqual(state.fields['/system'].next_utf8_byte,6);});
check('overlap_rejected',()=>assert.throws(()=>checkpointConfirm(state,pending(view('/system',1)),ack(),ref),/REPLAY_OR_OVERLAP/));
state=checkpointConfirm(state,pending(view('/system',2)),ack(),ref);
state=checkpointConfirm(state,pending(view('/user')),ack(),ref);
check('complete_unicode_roundtrip',()=>assert.strictEqual(checkpointWire(checkpointReconstruct(state,ref).fields),checkpointWire(state.fields)));
check('exact_replay_no_duplicate',()=>{const before=checkpointWire(state.fields);state=checkpointConfirm(state,pending(view('/system'),2),ack(),ref);assert.strictEqual(checkpointWire(state.fields),before);});
check('state_tamper_rejected',()=>{const x=copy(state);x.fields['/system'].content='edited';assert.throws(()=>checkpointReconstruct(x,ref),/OWN_CHECKPOINT_REPLAY/);});
check('same_cursor_retry',()=>{const p=pending(view('/user',0,4096));const before=checkpointWire(state.fields);const x=checkpointConfirm(state,p,ack(),ref);assert.strictEqual(checkpointWire(x.fields),before);});
check('complete_fields_sha256',()=>{for(const selector of ['/system','/user'])assert.strictEqual('sha256:'+ownViewSha256(state.fields[selector].content),input.field_hashes[selector]);});
check('exact_key_set_positive',()=>checkpointKeys({a:0,b:0},['a','b'],'EXACT'));
check('comma_key_collision_rejected',()=>assert.throws(()=>checkpointKeys({'a,b':0},['a','b'],'COLLISION'),/COLLISION/));
check('lone_surrogates_rejected',()=>{for(const value of ['\ud800','\udfff','x\ud800y'])assert.throws(()=>ownViewSha256(value),/NONSCALAR_OWN_FIELD/);});
check('independent_hash_vectors',()=>{assert.deepStrictEqual(input.hash_vectors.map(ownViewSha256),input.hash_expected);});
check('explicit_empty_fields_eof',()=>{fields['/system']='';fields['/user']='';let x=checkpointConfirm(undefined,pending(inv),ack(),ref);assert.strictEqual(x.fields['/system'].field_eof,false);assert.throws(()=>checkpointConfirm(x,pending(view('/user')),ack(),ref),/SYSTEM_EOF_REQUIRED/);x=checkpointConfirm(x,pending(view('/system')),ack(),ref);x=checkpointConfirm(x,pending(view('/user')),ack(),ref);assert.strictEqual(x.fields['/system'].field_eof,true);assert.strictEqual(x.fields['/user'].field_eof,true);assert.strictEqual(x.fields['/user'].content,'');});
console.log(JSON.stringify({format:'verislop.carrier003-independent-generic-source-controls/1',controls:results,control_count:results.length,hash_vector_count:input.hash_vectors.length,long_vector_chars:Array.from(input.hash_vectors.at(-1)).length,long_vector_utf8_bytes:checkpointText(input.hash_vectors.at(-1)).bytes,actual_VIEW_calls:0,model_calls:0,Lean_calls:0,qualification_authority:false}));
