import Std

-- BEGIN VERISLOP REGISTRY
-- Generated by `verislop formalize`. Typed obligation metadata: an index, never evidence.
namespace VeriSlop.Registry

structure SourceRef where
  documentRef : String
  documentHash : String
  startByte : Nat
  endByte : Nat
  origin : String
  interpretation : String

structure Dependency where
  id : String
  relation : String

structure Entry where
  id : String
  revision : Nat
  kind : String
  role : String
  statement : String
  required : Bool
  sourceRefs : List SourceRef
  scope : List String
  dependencies : List Dependency
  acceptanceCriteria : List String
  bindings : List String

def «G-map» : Entry := {
  id := "G-map",
  revision := 1,
  kind := "postcondition",
  role := "guarantee",
  statement := "For every finite list of Box, map each Box to a Box with the same tone and live flag and natural n increased by one.",
  required := true,
  sourceRefs := [{ documentRef := "validation/isolated-collection-bridge-20261010-gcb/specification.json", documentHash := "sha256:915d34e6883488ea3db8bb7986f5ed34ab9ac051c01a4e061513ec7adea46308", startByte := 0, endByte := 1934, origin := "explicit", interpretation := "Independent artificial collection fixture, persisted before inputs." }],
  scope := ["All declared values and arbitrary finite lists; normative source semantics."],
  dependencies := [],
  acceptanceCriteria := ["The exact universally quantified operation equation."],
  bindings := ["VeriSlopAST.law_raiseBoxes"] }

def «G-filter» : Entry := {
  id := "G-filter",
  revision := 1,
  kind := "postcondition",
  role := "guarantee",
  statement := "For every finite list of Box and every Atom needle, keep exactly the Boxes whose atom equals needle, preserving order and duplicates. Equality uses the formalizer-fixed canonical decidable equality.",
  required := true,
  sourceRefs := [{ documentRef := "validation/isolated-collection-bridge-20261010-gcb/specification.json", documentHash := "sha256:915d34e6883488ea3db8bb7986f5ed34ab9ac051c01a4e061513ec7adea46308", startByte := 0, endByte := 1934, origin := "explicit", interpretation := "Independent artificial collection fixture, persisted before inputs." }],
  scope := ["All declared values and arbitrary finite lists; normative source semantics."],
  dependencies := [],
  acceptanceCriteria := ["The exact universally quantified operation equation."],
  bindings := ["VeriSlopAST.law_keepAtom"] }

def «G-fold» : Entry := {
  id := "G-fold",
  revision := 1,
  kind := "postcondition",
  role := "guarantee",
  statement := "For every finite list of Box, left-fold from zero, adding atom.n exactly when atom.tone equals cold. Equality uses the formalizer-fixed canonical decidable equality.",
  required := true,
  sourceRefs := [{ documentRef := "validation/isolated-collection-bridge-20261010-gcb/specification.json", documentHash := "sha256:915d34e6883488ea3db8bb7986f5ed34ab9ac051c01a4e061513ec7adea46308", startByte := 0, endByte := 1934, origin := "explicit", interpretation := "Independent artificial collection fixture, persisted before inputs." }],
  scope := ["All declared values and arbitrary finite lists; normative source semantics."],
  dependencies := [],
  acceptanceCriteria := ["The exact universally quantified operation equation."],
  bindings := ["VeriSlopAST.law_coldTotal"] }

def entries : List Entry := [«G-map», «G-filter», «G-fold»]

end VeriSlop.Registry
-- END VERISLOP REGISTRY

namespace VeriSlopAST
inductive «Tone» where
  | «cold»
  | «warm»
  deriving _root_.DecidableEq
structure «Atom» where
  «tone» : _root_.VeriSlopAST.«Tone»
  «n» : _root_.Nat
structure «Box» where
  «atom» : _root_.VeriSlopAST.«Atom»
  «live» : _root_.Bool
def «coldTotal» («_v0» : (_root_.List _root_.VeriSlopAST.«Box»)) : _root_.Nat := (@_root_.List.foldl _root_.Nat _root_.VeriSlopAST.«Box» (fun («_v1» : _root_.Nat) («_v2» : _root_.VeriSlopAST.«Box») => (@_root_.cond _root_.Nat (@_root_.Decidable.decide ((_root_.VeriSlopAST.«Atom».«tone» (_root_.VeriSlopAST.«Box».«atom» «_v2»)) = _root_.VeriSlopAST.«Tone».«cold») (_root_.VeriSlopAST.«instDecidableEqTone» (_root_.VeriSlopAST.«Atom».«tone» (_root_.VeriSlopAST.«Box».«atom» «_v2»)) _root_.VeriSlopAST.«Tone».«cold»)) (_root_.Nat.add «_v1» (_root_.VeriSlopAST.«Atom».«n» (_root_.VeriSlopAST.«Box».«atom» «_v2»))) «_v1»)) (0 : _root_.Nat) «_v0»)
theorem «_vs_body_coldTotal» : (∀ («_v0» : (_root_.List _root_.VeriSlopAST.«Box»)), ((_root_.VeriSlopAST.«coldTotal» «_v0») = (@_root_.List.foldl _root_.Nat _root_.VeriSlopAST.«Box» (fun («_v1» : _root_.Nat) («_v2» : _root_.VeriSlopAST.«Box») => (@_root_.cond _root_.Nat (@_root_.Decidable.decide ((_root_.VeriSlopAST.«Atom».«tone» (_root_.VeriSlopAST.«Box».«atom» «_v2»)) = _root_.VeriSlopAST.«Tone».«cold») (_root_.VeriSlopAST.«instDecidableEqTone» (_root_.VeriSlopAST.«Atom».«tone» (_root_.VeriSlopAST.«Box».«atom» «_v2»)) _root_.VeriSlopAST.«Tone».«cold»)) (_root_.Nat.add «_v1» (_root_.VeriSlopAST.«Atom».«n» (_root_.VeriSlopAST.«Box».«atom» «_v2»))) «_v1»)) (0 : _root_.Nat) «_v0»))) := by intros; rfl
def «keepAtom» («_v0» : (_root_.List _root_.VeriSlopAST.«Box»)) («_v1» : _root_.VeriSlopAST.«Atom») : (_root_.List _root_.VeriSlopAST.«Box») := (@_root_.List.filter _root_.VeriSlopAST.«Box» (fun («_v2» : _root_.VeriSlopAST.«Box») => (_root_.Bool.and (@_root_.Decidable.decide ((_root_.VeriSlopAST.«Atom».«tone» (_root_.VeriSlopAST.«Box».«atom» «_v2»)) = (_root_.VeriSlopAST.«Atom».«tone» «_v1»)) (_root_.VeriSlopAST.«instDecidableEqTone» (_root_.VeriSlopAST.«Atom».«tone» (_root_.VeriSlopAST.«Box».«atom» «_v2»)) (_root_.VeriSlopAST.«Atom».«tone» «_v1»))) (_root_.Decidable.decide ((_root_.VeriSlopAST.«Atom».«n» (_root_.VeriSlopAST.«Box».«atom» «_v2»)) = (_root_.VeriSlopAST.«Atom».«n» «_v1»))))) «_v0»)
theorem «_vs_body_keepAtom» : (∀ («_v0» : (_root_.List _root_.VeriSlopAST.«Box»)), (∀ («_v1» : _root_.VeriSlopAST.«Atom»), ((_root_.VeriSlopAST.«keepAtom» «_v0» «_v1») = (@_root_.List.filter _root_.VeriSlopAST.«Box» (fun («_v2» : _root_.VeriSlopAST.«Box») => (_root_.Bool.and (@_root_.Decidable.decide ((_root_.VeriSlopAST.«Atom».«tone» (_root_.VeriSlopAST.«Box».«atom» «_v2»)) = (_root_.VeriSlopAST.«Atom».«tone» «_v1»)) (_root_.VeriSlopAST.«instDecidableEqTone» (_root_.VeriSlopAST.«Atom».«tone» (_root_.VeriSlopAST.«Box».«atom» «_v2»)) (_root_.VeriSlopAST.«Atom».«tone» «_v1»))) (_root_.Decidable.decide ((_root_.VeriSlopAST.«Atom».«n» (_root_.VeriSlopAST.«Box».«atom» «_v2»)) = (_root_.VeriSlopAST.«Atom».«n» «_v1»))))) «_v0»)))) := by intros; rfl
def «raiseBoxes» («_v0» : (_root_.List _root_.VeriSlopAST.«Box»)) : (_root_.List _root_.VeriSlopAST.«Box») := (@_root_.List.map _root_.VeriSlopAST.«Box» _root_.VeriSlopAST.«Box» (fun («_v1» : _root_.VeriSlopAST.«Box») => (_root_.VeriSlopAST.«Box».«mk» (_root_.VeriSlopAST.«Atom».«mk» (_root_.VeriSlopAST.«Atom».«tone» (_root_.VeriSlopAST.«Box».«atom» «_v1»)) (_root_.Nat.add (_root_.VeriSlopAST.«Atom».«n» (_root_.VeriSlopAST.«Box».«atom» «_v1»)) (1 : _root_.Nat))) (_root_.VeriSlopAST.«Box».«live» «_v1»))) «_v0»)
theorem «_vs_body_raiseBoxes» : (∀ («_v0» : (_root_.List _root_.VeriSlopAST.«Box»)), ((_root_.VeriSlopAST.«raiseBoxes» «_v0») = (@_root_.List.map _root_.VeriSlopAST.«Box» _root_.VeriSlopAST.«Box» (fun («_v1» : _root_.VeriSlopAST.«Box») => (_root_.VeriSlopAST.«Box».«mk» (_root_.VeriSlopAST.«Atom».«mk» (_root_.VeriSlopAST.«Atom».«tone» (_root_.VeriSlopAST.«Box».«atom» «_v1»)) (_root_.Nat.add (_root_.VeriSlopAST.«Atom».«n» (_root_.VeriSlopAST.«Box».«atom» «_v1»)) (1 : _root_.Nat))) (_root_.VeriSlopAST.«Box».«live» «_v1»))) «_v0»))) := by intros; rfl
theorem «law_coldTotal» : (∀ («_v0» : (_root_.List _root_.VeriSlopAST.«Box»)), ((_root_.VeriSlopAST.«coldTotal» «_v0») = (@_root_.List.foldl _root_.Nat _root_.VeriSlopAST.«Box» (fun («_v1» : _root_.Nat) («_v2» : _root_.VeriSlopAST.«Box») => (@_root_.cond _root_.Nat (@_root_.Decidable.decide ((_root_.VeriSlopAST.«Atom».«tone» (_root_.VeriSlopAST.«Box».«atom» «_v2»)) = _root_.VeriSlopAST.«Tone».«cold») (_root_.VeriSlopAST.«instDecidableEqTone» (_root_.VeriSlopAST.«Atom».«tone» (_root_.VeriSlopAST.«Box».«atom» «_v2»)) _root_.VeriSlopAST.«Tone».«cold»)) (_root_.Nat.add «_v1» (_root_.VeriSlopAST.«Atom».«n» (_root_.VeriSlopAST.«Box».«atom» «_v2»))) «_v1»)) (0 : _root_.Nat) «_v0»))) := by intros; rfl
theorem «law_keepAtom» : (∀ («_v0» : (_root_.List _root_.VeriSlopAST.«Box»)), (∀ («_v1» : _root_.VeriSlopAST.«Atom»), ((_root_.VeriSlopAST.«keepAtom» «_v0» «_v1») = (@_root_.List.filter _root_.VeriSlopAST.«Box» (fun («_v2» : _root_.VeriSlopAST.«Box») => (_root_.Bool.and (@_root_.Decidable.decide ((_root_.VeriSlopAST.«Atom».«tone» (_root_.VeriSlopAST.«Box».«atom» «_v2»)) = (_root_.VeriSlopAST.«Atom».«tone» «_v1»)) (_root_.VeriSlopAST.«instDecidableEqTone» (_root_.VeriSlopAST.«Atom».«tone» (_root_.VeriSlopAST.«Box».«atom» «_v2»)) (_root_.VeriSlopAST.«Atom».«tone» «_v1»))) (_root_.Decidable.decide ((_root_.VeriSlopAST.«Atom».«n» (_root_.VeriSlopAST.«Box».«atom» «_v2»)) = (_root_.VeriSlopAST.«Atom».«n» «_v1»))))) «_v0»)))) := by intros; rfl
theorem «law_raiseBoxes» : (∀ («_v0» : (_root_.List _root_.VeriSlopAST.«Box»)), ((_root_.VeriSlopAST.«raiseBoxes» «_v0») = (@_root_.List.map _root_.VeriSlopAST.«Box» _root_.VeriSlopAST.«Box» (fun («_v1» : _root_.VeriSlopAST.«Box») => (_root_.VeriSlopAST.«Box».«mk» (_root_.VeriSlopAST.«Atom».«mk» (_root_.VeriSlopAST.«Atom».«tone» (_root_.VeriSlopAST.«Box».«atom» «_v1»)) (_root_.Nat.add (_root_.VeriSlopAST.«Atom».«n» (_root_.VeriSlopAST.«Box».«atom» «_v1»)) (1 : _root_.Nat))) (_root_.VeriSlopAST.«Box».«live» «_v1»))) «_v0»))) := by intros; rfl
end VeriSlopAST
