import Std

-- BEGIN VERISLOP REGISTRY
-- Generated by `verislop formalize`. Typed obligation metadata: an index, never evidence.
namespace VeriSlop.Registry

structure SourceRef where
  documentRef : String
  documentHash : String
  startByte : Nat
  endByte : Nat
  origin : String
  interpretation : String

structure Dependency where
  id : String
  relation : String

structure Entry where
  id : String
  revision : Nat
  kind : String
  role : String
  statement : String
  required : Bool
  sourceRefs : List SourceRef
  scope : List String
  dependencies : List Dependency
  acceptanceCriteria : List String
  bindings : List String

def «D1» : Entry := {
  id := "D1",
  revision := 1,
  kind := "entity",
  role := "declaration",
  statement := "Fresh unrelated equality support fixture",
  required := true,
  sourceRefs := [],
  scope := ["generic-equality019"],
  dependencies := [],
  acceptanceCriteria := [],
  bindings := ["AdmissionEquality019.Indexed", "AdmissionEquality019.Recursive"] }

def «O1» : Entry := {
  id := "O1",
  revision := 1,
  kind := "postcondition",
  role := "guarantee",
  statement := "Fresh unrelated equality support fixture",
  required := true,
  sourceRefs := [],
  scope := ["generic-equality019"],
  dependencies := [],
  acceptanceCriteria := [],
  bindings := ["AdmissionEquality019.reflexive"] }

def entries : List Entry := [«D1», «O1»]

end VeriSlop.Registry
-- END VERISLOP REGISTRY

namespace AdmissionEquality019
structure Indexed where
  amount : Nat
  index : Fin amount
inductive Recursive where
  | base
  | step (previous : Recursive)
theorem reflexive (x : Indexed) : x = x := by rfl
end AdmissionEquality019
